//! Domain layer - core business logic (hexagonal architecture).
//!
//! This layer contains pure business logic independent of storage or UI.
//! All domain types are storage-agnostic and can be tested with mocks.

pub mod conventions;
pub mod frontmatter;
pub mod links;
pub mod prior_detect;
pub mod prior_distill;
pub mod prior_episode;
pub mod sessions;

use serde::{Deserialize, Serialize};

/// How a collection was created.
pub const COLLECTION_SOURCE_MANUAL: &str = "manual";
/// Collection was auto-detected via directory conventions.
pub const COLLECTION_SOURCE_CONVENTION: &str = "convention";
/// Collection was created for Claude Code session indexing.
pub const COLLECTION_SOURCE_SESSIONS: &str = "sessions";
/// Collection name for Claude Code sessions (excluded from default search).
pub const COLLECTION_CLAUDE_SESSIONS: &str = "claude_sessions";

/// A collection of documents from a directory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Collection {
    /// Unique name for this collection.
    pub name: String,

    /// Base path for the collection.
    pub path: String,

    /// Glob pattern for matching files.
    pub pattern: String,

    /// How this collection was created: "manual" or "convention".
    #[serde(default = "default_source")]
    pub source: String,

    /// Creation timestamp (Unix seconds).
    pub created_at: i64,

    /// Last update timestamp (Unix seconds).
    pub updated_at: i64,
}

fn default_source() -> String {
    COLLECTION_SOURCE_MANUAL.to_string()
}

/// A document in the knowledge base.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Document {
    /// Unique document ID.
    pub id: i64,

    /// Collection this document belongs to.
    pub collection: String,

    /// Relative path within the collection.
    pub relative_path: String,

    /// Content hash (SHA256).
    pub hash: String,

    /// Document title (from H1 or frontmatter).
    pub title: Option<String>,

    /// Parsed frontmatter metadata.
    pub metadata: Option<serde_json::Value>,

    /// File modification time (Unix seconds).
    pub file_modified_at: i64,

    /// Indexing time (Unix seconds).
    pub indexed_at: i64,

    /// Document status (current, superseded, retracted).
    pub status: Option<String>,
}

/// Search query parameters.
#[derive(Debug, Clone, Default)]
pub struct SearchQuery {
    /// The search text.
    pub text: String,

    /// Maximum results to return.
    pub limit: usize,

    /// Filter by collection name.
    pub collection: Option<String>,

    /// Filter by tags.
    pub tags: Vec<String>,

    /// Include superseded/retracted documents (default: false).
    pub include_superseded: bool,
}

/// A search result with score and snippets.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    /// Document ID.
    pub id: i64,

    /// Collection name.
    pub collection: String,

    /// Relative path.
    pub path: String,

    /// Document title.
    pub title: Option<String>,

    /// BM25 relevance score.
    pub score: f64,

    /// Matching snippets with highlights.
    pub snippets: Vec<String>,

    /// Document status (current, superseded, retracted).
    #[serde(default)]
    pub status: Option<String>,

    /// Path of document that superseded this one, if any.
    #[serde(default)]
    pub superseded_by: Option<String>,

    /// Repository root path (set in daemon mode for cross-repo search provenance).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo_root: Option<String>,
}

/// Index status information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndexStatus {
    /// Total number of collections.
    pub collections: usize,

    /// Total number of indexed documents.
    pub documents: usize,

    /// Number of stale documents needing reindex.
    pub stale_documents: usize,

    /// Database size in bytes.
    pub db_size_bytes: u64,

    /// Last update timestamp.
    pub last_updated: Option<i64>,
}

/// Result of an update operation.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateResult {
    /// Number of new documents indexed.
    pub added: usize,

    /// Number of documents updated (content changed).
    pub updated: usize,

    /// Number of documents removed (file deleted).
    pub removed: usize,

    /// Number of documents unchanged (skipped).
    pub unchanged: usize,

    /// Number of memory entries embedded by backfill during this update.
    #[serde(default)]
    pub memory_embeddings_backfilled: usize,

    /// Number of document embeddings generated by auto-embed during this update.
    #[serde(default)]
    pub doc_embeddings_generated: usize,

    /// Number of session documents archived because their source jsonl is gone.
    #[serde(default)]
    pub sessions_archived: usize,

    /// Memory entries backfilled to a markdown file (DB → file projection).
    #[serde(default)]
    pub memory_files_projected: usize,

    /// Memory entries inserted from a markdown file with no DB row — a
    /// colleague's entry arriving in a checkout.
    #[serde(default)]
    pub memory_files_imported: usize,

    /// Memory entries updated from their markdown file (file → DB).
    #[serde(default)]
    pub memory_files_adopted: usize,

    /// Entries where file and DB had both changed; the newer `updated_at` won
    /// and the loser was preserved in `memory_revisions`.
    #[serde(default)]
    pub memory_sync_conflicts: usize,

    /// Archived entries restored to active because their file reappeared.
    #[serde(default)]
    pub memory_entries_revived: usize,

    /// Markdown files skipped as unsafe to read (unresolved merge markers,
    /// unparseable frontmatter, id disagreeing with the filename).
    #[serde(default)]
    pub memory_files_quarantined: usize,

    /// Memory entries archived because their projected file was deleted.
    #[serde(default)]
    pub memory_entries_archived: usize,

    /// Archival candidates skipped because too many projected files vanished at
    /// once (suspected bulk loss, not deliberate deletion).
    #[serde(default)]
    pub memory_entries_archive_skipped: usize,

    /// Memory entries archived because they were past their `expires_at`.
    ///
    /// Separate from `memory_entries_archived`: that one reports a file the
    /// author deleted, this one reports a TTL the author set running out. The
    /// two answer different questions about where a store's entries went.
    #[serde(default)]
    pub memory_entries_expired: usize,

    /// Set when a `.gitignore` above the store excludes `.mdkb/` wholesale,
    /// making `.mdkb/.gitignore` inert and the entry projection untrackable.
    #[serde(default)]
    pub memory_gitignore_shadowed: Option<String>,

    /// Per-collection document counts after this run.
    ///
    /// A single total cannot distinguish "everything was re-indexed" from "one
    /// collection went to zero while another grew" — which is exactly the
    /// ambiguity that let 2307 documents vanish behind the word "indexed".
    #[serde(default)]
    pub collections: Vec<CollectionDelta>,

    /// Collections that held documents at the start of this run and are no
    /// longer registered. Named, never silently omitted.
    #[serde(default)]
    pub collections_vanished: Vec<String>,

    /// True when the store has no document collection registered at all. A run
    /// like that indexes nothing, and "Docs: 0 indexed" reads identically to a
    /// healthy no-op.
    #[serde(default)]
    pub no_collections_registered: bool,

    /// Errors encountered during indexing.
    pub errors: Vec<String>,
}

/// One collection's document count after an update.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollectionDelta {
    pub name: String,
    /// Documents currently indexed under this collection.
    pub documents: usize,
    /// Documents it held before this run, when that is known. `None` means the
    /// collection is new to this store.
    #[serde(default)]
    pub previous: Option<usize>,
}

impl UpdateResult {
    /// Total documents currently indexed in the scanned collections after this
    /// update: new + changed + unchanged (removed files are gone). Lets `update`
    /// report an honest doc-collection total, not just the per-run delta.
    pub fn docs_indexed(&self) -> usize {
        self.added + self.updated + self.unchanged
    }
}
